### ISSUE TITLE
onLoadHistory never called

### ISSUE THREAD

**Issue by sjd753** [RocketChat/Rocket.Chat.Java.SDK#27]
**chatRoom.getChatHistory(20, new Date(), null, this);**

**@Override
    public void onLoadHistory(List<RocketChatMessage> list, int unreadNotLoaded, ErrorObject error) {
        System.out.println("onLoadHistory size = " + list.size());     
}**

above is the callback which was never called by Rocket Chat although messages are printed in the log by System.out. Any ideas?

**Comment by sacOO7** [comment]
I have tested it very well, it should work. Can you put the code and log data in here 👍 , it will help me resolve the issue.

**Comment by sjd753** [comment]
Actually it does print the chat history in the log from Socket class but the callback never invoked! Although other API's getting the callbacks normally.

**Comment by sacOO7** [comment]
Hey can you write code like this
chatRoom.getChatHistory(50, null, null, this);

**Comment by sjd753** [comment]
Yes also tried this same result. I was calling   **chatRoom.getChatHistory(20, new Date(), null, this);** and **chatRoom.subscribeRoomMessageEvent(this, this);** at the same time. Guess this could be an issue so now calling subscribeRoom inside 
**@Override
public void onLoadHistory(List<RocketChatMessage> list, int unreadNotLoaded, ErrorObject error)** method. Hope it works. Let's see..

**Comment by sacOO7** [comment]
Calling any method any time shouldn't be an issue at all

**Comment by sacOO7** [comment]
Please refer this code

```
@Override
    public void onGetSubscriptions(List<SubscriptionObject> subscriptions, ErrorObject error) {
        ChatRoomFactory factory = api.getChatRoomFactory();
        RocketChatAPI.ChatRoom room = factory.createChatRooms(subscriptions).getChatRoomByName("general");
        room.getChatHistory(30, new Date(), null, this);
    }

    @Override
    public void onLoadHistory(List<RocketChatMessage> list, int unreadNotLoaded, ErrorObject error) {
        System.out.println("Got messages " + list.size());
        for (RocketChatMessage message : list) {
            System.out.println("Message is "+ message.getMessage());
        }
    }

```

**Comment by sacOO7** [comment]
Or you can refer to demo android app developed using java SDK, it used load history API without any problem having pagination.
Link to repo is https://github.com/RocketChat/RocketChat-Android-Demo

Link to the code is https://github.com/RocketChat/RocketChat-Android-Demo/blob/386f09098530ac0842056c69b006bcb7f2e14bf4/app/src/main/java/demo/rocketchat/example/ChatActivity.java#L118

**Comment by sjd753** [comment]
Yes that should work but what I did is that after creating the logical room I got the room list in a recyclerView then on item click I needed the room object in the next activity. So here is how i got the reference..

inside next (Chat) activities onCreate() 

**if (getIntent().hasExtra(EXTRA_ROOM_ID)) {
            roomId = getIntent().getStringExtra(EXTRA_ROOM_ID);
            RocketChatAPI api = RocketChatAPIHelper.getInstance().getApi();
            //Creating Logical ChatRooms using factory class
            ChatRoomFactory factory = api.getChatRoomFactory();
            chatRoom = factory.getChatRoomById(roomId);
            subscribeMessage();
        } else {
            Toast.makeText(this, "Something went wrong!", Toast.LENGTH_SHORT).show();
            onBackPressed();
        }**

Anything wrong with this?? And also I have check the chatRoom isn''t null and has the same roomId and works fine with other apis like sendMessage etc.

**Comment by sacOO7** [comment]
Can you put more code in here, maybe point to the repo if it is public. That way I can try to debug it in more detail .

**Comment by sacOO7** [comment]
Make sure you are processing onloadmore result on UI thread. That might create a problem.

**Comment by sjd753** [comment]
https://github.com/sjd753/RocketChatSDKDemo check this out! Also configure **RocketChatAPIHelper** class for setting up your server url (Must) and credentials (Optional)

**Comment by sacOO7** [comment]
Its not necessary to load history after subscription, you can load any time. Can you check if subscription is successful

**Comment by sjd753** [comment]
Yes subscription is always successful. Also history is printed from Socket class in the log meaning api is working only problem is the the callback in my activity isn't invoked!

**Comment by sacOO7** [comment]
Ohk can you put log here?

**Comment by sjd753** [comment]
Well more info after further testing found out that onLoadHistory is getting invoked only once for each room! Only for the first time! Second time you visit same room then not working. Visiting new room ..working! Weird!!

**Comment by sacOO7** [comment]
Please put history log here, there must be problem with handling threads

**Comment by sjd753** [comment]
Looks like **oldestMessageTimestamp** is the problem! passing new Date() there..so not returning those once returned for the forst time. See docs: 

/****
         * @param oldestMessageTimestamp Used to do pagination (null means latest timestamp)
         * @param count The message quantity, messages are loaded having timestamp older than @param oldestMessageTimestamp
         * @param lastTimestamp Date of the last time when client got data (Used to calculate unread)[unread count suggests number of unread messages having timestamp above @param lastTimestamp]
         **/

**Comment by sacOO7** [comment]
Thats obvious, or you can pass null in there. It will return latest entries equal to count. Although it doesn't matter how many time you call it. Please take a look at handling history using code on demo link I provided to you. run everything on UI thread for now.

**Comment by sjd753** [comment]
Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.DATE, -2);
        chatRoom.getChatHistory(200, calendar.getTime(), null, this);

Still not working for some rooms , some room working! Weird!

**Comment by sacOO7** [comment]
Keep trying, refer my code. Run it on emulator. You will get the idea.

**Comment by sacOO7** [comment]
For debugging purpose you can use Java IDE instead, run every method under main method

**Comment by sjd753** [comment]
Looks like the issue is resolved! Did you guys do something from the back-end? Also the ordering of the messages are now corrected. Thanks a lot for your time and efforts and Rocket Chat Team! #HappyCoding!

**Comment by sacOO7** [comment]
Hey thanks 👍  Let us know if you have any further issues :)

**Comment by Jahury** [comment]
Im still facing the same issue with some rooms.
BTW, Im using my own host for the server side.

**Comment by Jahury** [comment]
I found the problem, it was because some messages comes with an attachments , and the value of the attachments key  is null, so it tries use this value then an exception is thrown, and never reach the callback.
The problem is in the constractor of this class "RocketChatMessage" 
 
here exactly >>if (object.opt("attachments") != null) {
                attachments = new ArrayList<>();
                JSONArray array = object.optJSONArray("attachments");


if you just wrapper it with try and catch ,it will solve the problem.
